Acceptance tests: don’t use `managehome`
`managehome => true` breaks on macOS runners in GitHub CI:

> Error: Parameter managehome failed on User\[user\]: User provider
> directoryservice can not manage home directories